### ISSUE TITLE
Managing both 64-bit and 32-bit not working

### ISSUE THREAD

**Issue by camjac251** [theChaosCoder/VSRepoGUI#2]
I was hoping to use this tool with both 32-bit and 64-bit but found a bug in trying.

I toggled on 64-bit and installed QTGMC which installs the script into `AvisynthRepository\SCRIPTS` and plugins went to `AvisynthRepository\AVSPLUS_x64\plugins`
Although what I think is happening is that both my 32-bit and 64-bit scripts folders are set to the same path so it might think QTGMC is installed without checking dependencies first on 32-bit, when it's installed first on 64-bit.

**Comment by camjac251** [comment]
I only tried Avisynth. I'm not sure if the problem also exists in the Vapoursynth version

**Comment by theChaosCoder** [comment]
There was a bug where on start sometimes 32bit plugins were shown instead of 64bit (and maybe paths were mixed up too). It is fixed but no avsrepogui was released since. 

This would be a good time to finish my avisynth installation detection + selection window and make a new release.

**Comment by theChaosCoder** [comment]
Is fixed in the latest release.
