### ISSUE TITLE
CPU core reporting is wrong.

### ISSUE THREAD

**Issue by gcs8** [theChaosCoder/VSRepoGUI#4]
I have dual E5-2673 v4's so it should report 40 cores / 80 threads depending on how you are counting. 

OS: Microsoft Windows 10 Pro
Is 64Bit OS?: True
GPU: NVIDIA Quadro P4000
CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
CPU Cores: 32

![image](https://user-images.githubusercontent.com/64696803/88220306-cc853580-cc30-11ea-9ec6-6138a2f48884.png)

**Comment by theChaosCoder** [comment]
Seems to be the same problem as described [here](https://stackoverflow.com/questions/27965962/c-sharp-environment-processorcount-does-not-always-return-the-full-number-of-log)
VSRepoGUI also uses **System.Environment.ProcessorCount**

This test version [VSRepoGUI_cpu_core_test.zip](https://github.com/theChaosCoder/VSRepoGUI/files/4962372/VSRepoGUI_cpu_core_test.zip) should report the same numbers as shown in your image.
Please test and report.

**Comment by gcs8** [comment]
So, not quite, it looks like it is not counting / adding quantities. Looks like it is only counting GPU and CPU 0 but not 1.

![image](https://user-images.githubusercontent.com/64696803/88238597-0c0f4a00-cc50-11ea-9cc7-7b2859f6468d.png)

**Comment by theChaosCoder** [comment]
Ahh yes Sockets = 2

Can you show me what the output looks like on your machine with this:
[VSRepoGUI_Win32_Processor_output.zip](https://github.com/theChaosCoder/VSRepoGUI/files/4964245/VSRepoGUI_Win32_Processor_output.zip)

It will list everything from the Win32_Processor WMI class. I need to know how the output looks like on your machine,

**Comment by gcs8** [comment]
`/!\ Only Plugins and no Scripts are tested /!\
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R50
API R3.6
Options: -


OS: Microsoft Windows 10 Pro
Is 64Bit OS: Yes
GPU: NVIDIA Quadro P4000
CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
CPU Cores: 20
Logical Processors: 40

Win32_Processor Output
-------------------------------

AddressWidth: 64
Architecture: 9
AssetTag: 
Availability: 3
Caption: Intel64 Family 6 Model 79 Stepping 1
Characteristics: 252
ConfigManagerErrorCode: 
ConfigManagerUserConfig: 
CpuStatus: 1
CreationClassName: Win32_Processor
CurrentClockSpeed: 2295
CurrentVoltage: 7
DataWidth: 64
Description: Intel64 Family 6 Model 79 Stepping 1
DeviceID: CPU0
ErrorCleared: 
ErrorDescription: 
ExtClock: 100
Family: 179
InstallDate: 
L2CacheSize: 5120
L2CacheSpeed: 
L3CacheSize: 51200
L3CacheSpeed: 0
LastErrorCode: 
Level: 6
LoadPercentage: 100
Manufacturer: GenuineIntel
MaxClockSpeed: 2295
Name: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
NumberOfCores: 20
NumberOfEnabledCore: 20
NumberOfLogicalProcessors: 40
OtherFamilyDescription: 
PartNumber: 
PNPDeviceID: 
PowerManagementCapabilities: 
PowerManagementSupported: False
ProcessorId: BFEBFBFF000406F1
ProcessorType: 3
Revision: 20225
Role: CPU
SecondLevelAddressTranslationExtensions: False
SerialNumber: 
SocketDesignation: CPU0
Status: OK
StatusInfo: 3
Stepping: 
SystemCreationClassName: Win32_ComputerSystem
SystemName: WASHU
ThreadCount: 40
UniqueId: 
UpgradeMethod: 43
Version: 
VirtualizationFirmwareEnabled: False
VMMonitorModeExtensions: False
VoltageCaps: 
AddressWidth: 64
Architecture: 9
AssetTag: 
Availability: 3
Caption: Intel64 Family 6 Model 79 Stepping 1
Characteristics: 252
ConfigManagerErrorCode: 
ConfigManagerUserConfig: 
CpuStatus: 1
CreationClassName: Win32_Processor
CurrentClockSpeed: 2295
CurrentVoltage: 7
DataWidth: 64
Description: Intel64 Family 6 Model 79 Stepping 1
DeviceID: CPU1
ErrorCleared: 
ErrorDescription: 
ExtClock: 100
Family: 179
InstallDate: 
L2CacheSize: 5120
L2CacheSpeed: 
L3CacheSize: 51200
L3CacheSpeed: 0
LastErrorCode: 
Level: 6
LoadPercentage: 100
Manufacturer: GenuineIntel
MaxClockSpeed: 2295
Name: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
NumberOfCores: 20
NumberOfEnabledCore: 20
NumberOfLogicalProcessors: 40
OtherFamilyDescription: 
PartNumber: 
PNPDeviceID: 
PowerManagementCapabilities: 
PowerManagementSupported: False
ProcessorId: BFEBFBFF000406F1
ProcessorType: 3
Revision: 20225
Role: CPU
SecondLevelAddressTranslationExtensions: False
SerialNumber: 
SocketDesignation: CPU1
Status: OK
StatusInfo: 3
Stepping: 
SystemCreationClassName: Win32_ComputerSystem
SystemName: WASHU
ThreadCount: 40
UniqueId: 
UpgradeMethod: 43
Version: 
VirtualizationFirmwareEnabled: False
VMMonitorModeExtensions: False
VoltageCaps: `

**Comment by theChaosCoder** [comment]
Last test I hope 
[VSRepoGUI_cpu2.zip](https://github.com/theChaosCoder/VSRepoGUI/files/4968259/VSRepoGUI_cpu2.zip)

**Comment by gcs8** [comment]
woooo, guess my only other question is would it be worth your time to report the qty of CPUs/GPUs?

`/!\ Only Plugins and no Scripts are tested /!\
VapourSynth Video Processing Library
Copyright (c) 2012-2020 Fredrik Mellbin
Core R50
API R3.6
Options: -


OS: Microsoft Windows 10 Pro
Is 64Bit OS: Yes
GPU: NVIDIA Quadro P4000
CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
CPU Cores: 40
Logical Processors: 80`

**Comment by theChaosCoder** [comment]
Something like this?
```
GPU1: NVIDIA Quadro P4000
GPU2: NVIDIA GeForce GTX 1070
CPU: Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz       
CPU Cores: 40
Logical Processors: 80
Sockets: 2 or CPUs: 2
```

**Comment by gcs8** [comment]
Maybe something like this? (sorry for the bad pseudo code)

```GPU(s) #
if GPUs = identical print Model x#
else print list

CPU: mfg + series + model @ speed + qty if <1
Cores #
LPs (threads)#
Sockets AND/OR NUMA nodes
RAM in GiB```

**Comment by theChaosCoder** [comment]
I don't want to show to much details. There are better tools for showing detailed cpu gpu information. 

Please check if the output looks ok and it doesn't crash. Can't really test here with multiple cpus/gpus...

This is how it looks on my machine

```
OS: Microsoft Windows 10 Enterprise
64Bit OS: Yes
GPU: NVIDIA GeForce GTX 1070
CPU: AMD Ryzen 5 2600 Six-Core Processor            
CPU Cores: 6
Logical Processors: 12
RAM: 32 GB
```

**Comment by gcs8** [comment]
Did you mean to attach another test file?

**Comment by theChaosCoder** [comment]
Yes :D
[VSRepoGUI_cpu3.zip](https://github.com/theChaosCoder/VSRepoGUI/files/4975611/VSRepoGUI_cpu3.zip)

**Comment by gcs8** [comment]
looks like it is not counting right

![image](https://user-images.githubusercontent.com/64696803/88457782-44cd4000-ce57-11ea-8f0a-19c4e089eebb.png)

**Comment by theChaosCoder** [comment]
That's a lot of ram 😲
[VSRepoGUI_cpu4.zip](https://github.com/theChaosCoder/VSRepoGUI/files/4975633/VSRepoGUI_cpu4.zip)

**Comment by gcs8** [comment]
Yeah, it is nice to have.

![image](https://user-images.githubusercontent.com/64696803/88458800-8ad9d200-ce5e-11ea-9e6f-ddc0654ad644.png)

**Comment by gcs8** [comment]
Cool, anything else I can test or make extra work for you? If not I will close this out.

**Comment by theChaosCoder** [comment]
hehe, I think you can close it. At least I don't miss any feature.
