### ISSUE TITLE
Dependencies not installing

### ISSUE THREAD

**Issue by Ironclad17** [theChaosCoder/VSRepoGUI#8]
Installing havsfunc and muvsfunc did not install several dependencies. Havsfunc was installed without vsutil installing. Several muvsfunc plugins also did not install including: AWarpSharp2, Bilateral, CAS, CTMF, descale, TCanny, and likely many others. All are listed separately in Vsrepogui.  VSrepogui was placed in the the pedeps bin directory with listpedeps.exe. Diagnose Problems did not recognize the missing dependencies.

**Comment by Ironclad17** [comment]
Dependencies for kagefunc also missing.

**Comment by theChaosCoder** [comment]
This is a vsrepo issue not a vsrepo-gui issue.

The pedeps depency check will not (and can not) detect missing plugins for a script. It only checks for "hard depencies" like runtimes, cuda lib etc for dlls.

Which plugins / script are missing for kagefunc?

**Comment by Ironclad17** [comment]
I think adaptivegrain, addgrain, bm3d, descale, fmtconv, retinex, tcanny, bilateral, detest, sangnom, yadifmod, ffms2, fftw, , mvtools, fft3dfilter, retinex, and wwxd. Wwxd was not listed in vsrepo.

**Comment by theChaosCoder** [comment]
I don't see any missing deps in kagefunc https://github.com/Irrational-Encoding-Wizardry/kagefunc/blob/master/kagefunc.py

These are the current defined deps https://github.com/vapoursynth/vsrepo/blob/master/local/kagefunc.json#L11

```
"dependencies": [
		"mvsfunc",
		"fvsfunc",
		"tegaf.asi.xe",
		"fmtconv",
		"com.invalid.identifier.retinex",
		"com.vapoursynth.bm3d",
		"com.Khanattila.KNLMeansCL",
		"com.holywu.tcanny",
		"com.holywu.addgrain",
		"vsutil"
	],
```

adaptivegrain is a function in kagefunc, not a plugin
There's no usage of bilateral, detest, sangnom, yadifmod, ffms2, fftw, mvtools, fft3dfilter in kagefunc
Not sure what problems you have with kagefunc...

Wwxd is not in the repository (and also not used in kagefunc)
What is detest?

**Comment by Ironclad17** [comment]
I was going by the dependencies listed in AUR. I also included the dependencies within the dependencies.
https://aur.archlinux.org/packages/vapoursynth-plugin-kagefunc-git

**Comment by theChaosCoder** [comment]
They probably only added dependencies but never removed unused ones. The script had some drastic changes over the years.

**Comment by Ironclad17** [comment]
https://github.com/vapoursynth/vsrepo/blob/master/local/fvsfunc.json

> "dependencies": [
> 		"havsfunc",
> 		"mvsfunc",
> 		"muvsfunc",
> 		"nnedi3_rpow2",
> 		"edi_rpow2",
> 		"com.deinterlace.nnedi3",
> 		"fmtconv",
> 		"com.invalid.identifier.bilateral",
> 		"com.wolframrhodium.bilateralGPU",
> 		"com.holywu.dfttest",
> 		"tegaf.asi.xe",
> 		"com.vapoursynth.ffms2",
> 		"systems.innocent.fft3dfilter",
> 		"com.nodame.mvtools",
> 		"com.mio.sangnom",
> 		"com.holywu.yadifmod"
> 	],

**Comment by theChaosCoder** [comment]
Big plugin dependencies update in vsrepo https://github.com/vapoursynth/vsrepo/commit/3ba23b38fb5723a99b5eb187f0ff35149165bbbe
