### ISSUE TITLE
Default plugins and scripts directory in Windows is in Roaming instead of Local

### ISSUE THREAD

**Issue by Ironclad17** [theChaosCoder/VSRepoGUI#9]
Causes some confusion as the default directory when installing for a single user in Windows will be in AppData\Local\Programs\
for both Python and Vapoursynth

**Comment by theChaosCoder** [comment]
This is how Vapoursynth handles plugins http://www.vapoursynth.com/doc/installation.html?highlight=roaming#plugin-autoloading
